# Site
title: MeetUnion Blog                # 网站标题
subtitle: 个人博客                    # 网站子标题
description:                          # 网站描述
keywords:                              # 网站关键字
author: MeetUnion                      # 作者
language: zh-CN                        # 语言
timezone: Asia/Shanghai                # 时区

# URL
url: https://meetingunion.github.io/MetaBeta/
root: /skills-github-pages/
permalink: :year/:month/:day/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
    enable: true
    line_number: true
    auto_detect: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: reimu

# Deployment
deploy:
  type: git
  repo: https://github.com/MeetingUnion/MetaBeta
  branch: main
